create table if not exists public.registration_attempts (
  id bigint generated by default as identity primary key,
  ip_hash text not null,
  attempted_at timestamptz not null default now(),
  succeeded boolean not null default false
);

alter table public.registration_attempts enable row level security;

revoke all on table public.registration_attempts from anon, authenticated;
grant select, insert, update, delete on table public.registration_attempts to service_role;
grant usage, select on sequence public.registration_attempts_id_seq to service_role;

create index if not exists registration_attempts_ip_time_idx
  on public.registration_attempts (ip_hash, attempted_at desc);
